name: Opus-tools Win64 Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 pkg-config autoconf automake libtool-bin gettext make zip

      - name: Create Build Environment
        run: |
          mkdir -p ${{ github.workspace }}/local_dist
          mkdir -p build_output/Win64

      - name: Build libogg
        run: |
          git clone https://github.com/xiph/ogg.git
          cd ogg
          git describe --tags --always > .tarball-version
          ./autogen.sh
          ./configure --host=x86_64-w64-mingw32 --prefix=${{ github.workspace }}/local_dist \
                      --enable-static --disable-shared \
                      CFLAGS="-O3 -march=x86-64-v3 -flto -ffunction-sections -fdata-sections" \
                      LDFLAGS="-flto -Wl,--gc-sections -Wl,-O1"
          make -j$(nproc) install

      - name: Build libopus
        run: |
          git clone https://github.com/xiph/opus.git
          cd opus
          git describe --tags --always > .tarball-version
          ./autogen.sh
          ./configure --host=x86_64-w64-mingw32 --prefix=${{ github.workspace }}/local_dist \
                      --enable-static --disable-shared --enable-osce --enable-dred --enable-qext\
                      --disable-doc --disable-extra-programs --disable-rtcd --disable-intrinsics\
                      CFLAGS="-O3 -march=x86-64-v3 -flto -ffunction-sections -fdata-sections" \
                      LDFLAGS="-flto -Wl,--gc-sections -Wl,-O1"
          make -j$(nproc) install

      - name: Build libflac
        run: |
          git clone https://github.com/xiph/flac.git
          cd flac
          git describe --tags --always > .tarball-version
          libtoolize --force
          ./autogen.sh
          export PKG_CONFIG_PATH=${{ github.workspace }}/local_dist/lib/pkgconfig
          ./configure --host=x86_64-w64-mingw32 --prefix=${{ github.workspace }}/local_dist \
                      --enable-static --disable-shared --disable-cpplibs --disable-examples \
                      --disable-doxygen-docs --disable-thorough-tests \
                      CFLAGS="-O3 -march=x86-64-v3 -flto -ffunction-sections -fdata-sections" \
                      LDFLAGS="-flto -Wl,--gc-sections -Wl,-O1"
          make -j$(nproc) install

      - name: Build libopusfile
        run: |
          git clone https://github.com/xiph/opusfile.git
          cd opusfile
          git describe --tags --always > .tarball-version
          ./autogen.sh
          export PKG_CONFIG_PATH=${{ github.workspace }}/local_dist/lib/pkgconfig
          ./configure --host=x86_64-w64-mingw32 --prefix=${{ github.workspace }}/local_dist \
                      --enable-static --disable-shared --disable-http \
                      --disable-examples --disable-doc \
                      CFLAGS="-O3 -march=x86-64-v3 -flto -ffunction-sections -fdata-sections" \
                      LDFLAGS="-flto -Wl,--gc-sections -Wl,-O1"
          make -j$(nproc) install

      - name: Build libopusenc
        run: |
          git clone https://github.com/xiph/libopusenc.git
          cd libopusenc
          git describe --tags --always > .tarball-version
          ./autogen.sh
          export PKG_CONFIG_PATH=${{ github.workspace }}/local_dist/lib/pkgconfig
          ./configure --host=x86_64-w64-mingw32 --prefix=${{ github.workspace }}/local_dist \
                      --enable-static --disable-shared \
                      --disable-examples --disable-doc \
                      CFLAGS="-O3 -march=x86-64-v3 -flto -ffunction-sections -fdata-sections" \
                      LDFLAGS="-flto -Wl,--gc-sections -Wl,-O1"
          make -j$(nproc) install

      - name: Build opus-tools
        run: |
          git clone https://github.com/xiph/opus-tools.git
          cd opus-tools
          git describe --tags --always > .tarball-version
          ./autogen.sh
          
          export PKG_CONFIG_PATH=${{ github.workspace }}/local_dist/lib/pkgconfig
          export CPPFLAGS="-I${{ github.workspace }}/local_dist/include -DFLAC__NO_DLL"
          export LIBS="-logg"
          
          ./configure --host=x86_64-w64-mingw32 \
                      CFLAGS="-O3 -march=x86-64-v3 -flto -ffunction-sections -fdata-sections" \
                      LDFLAGS="-L${{ github.workspace }}/local_dist/lib -static -flto -Wl,--gc-sections -Wl,-O1" \
                      FLAC_CFLAGS="-I${{ github.workspace }}/local_dist/include -DFLAC__NO_DLL" \
                      FLAC_LIBS="-L${{ github.workspace }}/local_dist/lib -lFLAC -logg"
          make -j$(nproc)
          
          cp *.exe ${{ github.workspace }}/build_output/Win64/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@main
        with:
          name: opus-tools-win64
          path: build_output/
